ARG CUDA_BASE_IMAGE=nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
FROM ${CUDA_BASE_IMAGE}

LABEL maintainer="Ngoc Ho" \
      description="Container with runtime and system dependencies for CaMo-JEPA"

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=UTC \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    CONDA_DIR=/opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH

# ===== System/APT packages needed for compiling extensions and executing pipelines =====
RUN apt-get update && apt-get install -y --no-install-recommends \
        locales tzdata \
        curl gnupg lsb-release git wget vim \
        software-properties-common \
        build-essential \
        ca-certificates \
        ffmpeg \
        swig \
        cmake \
        libgl1 \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender1 \
        libsdl2-2.0-0 \
        libsdl2-dev \
        libjpeg-dev \
        zlib1g-dev \
        gdal-bin \
        libgdal-dev \
        libgeos-dev \
        libproj-dev \
        libspatialindex-dev \
        proj-bin \
        proj-data \
        openmpi-bin \
        libopenmpi-dev \
    && locale-gen en_US.UTF-8 \
    && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get remove -y python3-sympy 2>/dev/null || true

# ===== Install Miniconda (Base conda system) =====
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    bash /tmp/miniconda.sh -b -p $CONDA_DIR && \
    rm /tmp/miniconda.sh

RUN conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

WORKDIR /workspace

CMD ["/bin/bash"]

# podman build -t cuda11_8_0-cudnn8-runtime-ubuntu22_04:base -f Dockerfile.camo_jepa .
# enroot import -o cuda11_8_0-cudnn8-runtime-ubuntu22_04.sqsh podman://cuda11_8_0-cudnn8-runtime-ubuntu22_04:base
